### ISSUE TITLE
LazyGit seem not to work on my PC

### ISSUE THREAD

**Issue by BolajiAyodeji** [SarathSantoshDamaraju/lazyGit#16]
Okay, this is my first time using aliases.
I cloned this Repo into a custom directory and ran `./_install` in it.
I got the installation success message.
I tried to run the short commands, but I got errors `bash command does not exist`

Can you provide a clearer installation method for aliases newbies?
Is there a directory i should clone to or  run `./_install`?

Thank you!

**Comment by SarathSantoshDamaraju** [comment]
You can install the file from anywhere. What is the OS you tried installing it on?

**Comment by BolajiAyodeji** [comment]
WINDOWS!

I think its working now, but it didn't work after i installed it.
Is that how it ought to be?
Thank you!

**Comment by SarathSantoshDamaraju** [comment]
Great, It works after you re-open your terminal.

**Comment by SarathSantoshDamaraju** [comment]
Updated [Readme](https://github.com/SarathSantoshDamaraju/lazyGit/commit/fc21d3f49998efbbb525b400999bfa8c2f5abf9e)

Thank you :)
