### ISSUE TITLE
Chained commands

### ISSUE THREAD

**Issue by EQuineOntology** [SarathSantoshDamaraju/lazyGit#3]
Hi! Many thanks for sharing the repository, helped me clean up my own aliases quite a bit :)

I was wondering: some commands can be reasonably chained depending on your workflow - for instance I tend to work on one thing at a time, so I often run `git add . ` and `git commit -m` together, which could be aliased in lazyGit with something like `g.c`, `gca`, or `gac` depending on the format you prefer. Would you accept a pull request for that? And if so, any preference on the name? I would probably use `gac` as short for "git/add/commit" but I'm open to suggestions

**Comment by SarathSantoshDamaraju** [comment]
Hi @HHErebus , Sounds good to me; go ahead and raise a PR.
And sorry for the late reply

**Comment by EQuineOntology** [comment]
Added in [PR#4](https://github.com/SarathSantoshDamaraju/lazyGit/pull/4), in the end  I went with `g.c` as it is more consistent with the already existing commands. Many thanks for the repo again :)
